version: "3.3"
services:
  mysql:
    restart: always
    build:
      context: .
      dockerfile: extra/mysql/Dockerfile
      #args:
      #  MODE: prod
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  cache:
    restart: always
    build:
      context: .
      dockerfile: extra/cache/Dockerfile
      #args:
      #  MODE: prod
    ports:
      - 11211

  hhvm:
    restart: always
    build:
      context: .
      dockerfile: extra/hhvm/Dockerfile
      #args:
      #  MODE: prod
    depends_on:
      - mysql
      - cache
    ports:
      - 9000

  nginx:
    restart: always
    build:
      context: .
      dockerfile: extra/nginx/Dockerfile
      #args:
      #  MODE: prod
    depends_on:
      - hhvm
    ports:
      - 80:80
      - 443:443
